name = "nivis"
description = "A clean zola theme for bloggers"
tags = ["clean"]
license = "MIT"
homepage = "https://github.com/Resorie/zola-theme-nivis"
demo = "https://resorie.github.io/blog/"
# The minimum version of Zola required
min_version = "0.21.0"

# Any variable there can be overriden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]
main_section = "blog"

# The theme author info: you!
[author]
name = "Resory"
homepage = "https://resorie.github.io/blog/"
